<?php

require_once "model/Member.php";
require_once "controller/MyController.php";

class ControllerUser extends MyController
{

    public function index(): void
    {
        $currentUser=$this->get_user_or_redirect();

        (new View("settings"))->show(['currentUser'=>$currentUser]);
    }

    public function logout(): void
    {
        parent::logout(); // TODO: Change the autogenerated stub
    }
    public function change_password(): void {
        $currentUser=$this->get_user_or_redirect();

        (new View("change_password"))->show(['currentUser'=>$currentUser]);
    }

    public function edit_profil() : void {
        $currentUser=$this->get_user_or_redirect();

        (new View("edit_profil"))->show(['currentUser'=>$currentUser]);
    }

}