<?php

class MyController extends Controller
{

    public function index(): void
    {
        // TODO: Implement index() method.
    }
    public function get_user_or_redirect(): Member
    {
        return parent::get_user_or_redirect(); // TODO: Change the autogenerated stub
    }
}